myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    # トップページのリンク
    path('likeordering', views.Indexlike.as_view(), name='indexlike'),
    # トップページのリンク(いいねの多い順)
    path('mypage', views.Mypage.as_view(), name='mypage'),
    # マイページのリンク
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    # 新規投稿ページのリンク
    path(
        'post_detail/<int:pk>',
        views.PostDetail.as_view(),
        name='post_detail'),
    # 詳細画面表示
    path(
        'post_update/<int:pk>',
        views.PostUpdate.as_view(),
        name='post_update'),
    # 更新画面表示
    path(
        'post_delete/<int:pk>',
        views.PostDelete.as_view(),
        name='post_delete'),
    # 削除画面
    path('post_list', views.PostList.as_view(), name='post_list'),
    # リスト画面
    path('login', views.Login.as_view(), name='login'),
    # ログイン画面
    path('logout', views.Logout.as_view(), name='logout'),
    # ログアウト画面
    path('signup', views.SignUp.as_view(), name='signup'),
    # サインアップ画面
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('dislike/<int:post_id>', views.DisLike_add, name='dislike_add'),
    # いいね・よくないね
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path(
        'category_detail/<str:name_en>',
        views.CategoryDetail.as_view(),
        name='category_detail'),
    # カテゴリー
    path('tag_list', views.TagList.as_view(), name='tag_list'),
    path(
        'tag_detail/<str:name>',
        views.TagDetail.as_view(),
        name='tag_detail'),
    # タグ
    path('search', views.Search, name='search'),
    # 検索


]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 追記

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

# Create your models here.


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category=self).count()
        return n

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('タイトル', max_length=50)
    content = RichTextUploadingField('内容', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    
    def like_count(self):
        n = Like.objects.filter(post=self).count()
        return n

    def dislike_count(self):
        n = DisLike.objects.filter(post=self).count()
        return n

    def get_previous_by_pk(self):
        queryset = type(self).objects.filter(pk__lt=self.pk).order_by('pk').last()
        if queryset:
            return queryset
        else:
            raise self.DoesNotExist("%s matching query does not exist." % self.__class__._meta.object_name)

    def get_next_by_pk(self):
        queryset = type(self).objects.filter(pk__gt=self.pk).order_by('pk').first()
        if queryset:
            return queryset
        else:
            raise self.DoesNotExist("%s matching query does not exist." % self.__class__._meta.object_name)

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="投稿",
        on_delete=models.CASCADE)
    user = models.ForeignKey(
        User,
        verbose_name="LIKEしたユーザー",
        on_delete=models.CASCADE)


class DisLike(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="投稿",
        on_delete=models.CASCADE)
    user = models.ForeignKey(
        User,
        verbose_name="DisLIKEしたユーザー",
        on_delete=models.CASCADE)

myapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'tags', 'thumbnail')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1, max_length=30, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

myapp/views.py
from django.shortcuts import resolve_url, redirect, render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category, DisLike
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from taggit.models import Tag
from django.db.models import Count
# from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        post = Post.objects.get(id=self.kwargs['pk'])
        return post.author == self.request.user


class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')
        context = {
            'post_list': post_list,
        }
        return context


class Mypage(TemplateView):
    template_name = 'myapp/mypage.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')
        context = {
            'post_list': post_list,
        }
        return context


class Indexlike(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-like')
        context = {
            'post_list': post_list,
        }
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

        def get_success_url(self):
            messages.success(self.request, 'Postを登録しました。')
            return resolve_url('myapp:index')


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs['pk'])
        category_posts = Post.objects.filter(
            category=detail_data.category).order_by('-created_at')
        related_items = self.object.tags.similar_objects()

        params = {
            'object': detail_data,
            'category_posts': category_posts,
            'related_items': related_items,
        }
        return params


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, 'Postを更新しました。')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])


class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.warning(self.request, 'Postを削除しました。')
        return resolve_url('myapp:index')


class PostList(ListView):
    paginate_by = 10
    model = Post

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'


class Logout(LogoutView):
    template_name = 'myapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.success(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id=post_id)

    is_liked = Like.objects.filter(user=request.user, post=post_id).count()
    like = Like()
    url = request.META.get('HTTP_REFERER')

    if is_liked > 0:
        messages.info(request, 'いいねを取り消しました。')
        Like.objects.filter(user=request.user, post=post_id).delete()
        return redirect(url)

    else:
        like.user = request.user
        like.post = post
        like.save()

        messages.success(request, '投稿にいいねしました！')
        return redirect(url)


@login_required
def DisLike_add(request, post_id):
    post = Post.objects.get(id=post_id)
    dislike = DisLike()
    is_disliked = DisLike.objects.filter(
        user=request.user, post=post_id).count()
    url = request.META.get('HTTP_REFERER')

    if is_disliked > 0:
        messages.info(request, 'よくないねを取り消しました。')
        DisLike.objects.filter(user=request.user, post=post_id).delete()
        return redirect(url)

    else:
        dislike.user = request.user
        dislike.post = post
        dislike.save()

        messages.warning(request, 'よくないねしました。')
        return redirect(url)


class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs['name_en'])
        category_posts = Post.objects.filter(
            category=detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


class TagList(ListView):
    model = Tag


class TagDetail(DetailView):
    model = Tag
    slug_field = 'name'
    slug_url_kwarg = 'name'

    def get_context_data(self, *args, **kwargs):
        tag_lists = Tag.objects.all().annotate(blog_count=Count(
            'taggit_taggeditem_items')).order_by('-blog_count')
        tag = Tag.objects.get(name=self.kwargs['name'])
        tag_posts = Post.objects.filter(tags=tag)

        params = {
            'tag': tag,
            'tag_lists': tag_lists,
            'tag_posts': tag_posts,
        }
        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = Post.objects.filter(Q(title__icontains=freeword) | Q(
                content__icontains=freeword) | Q(
                author__username__icontains=freeword) | Q(
                    category__name__icontains=freeword) | Q(
                        tags__name__icontains=freeword)).distinct()

        params = {
            'search_list': search_list,
        }

        return render(request, 'myapp/search.html', params)


# Create your views here.

myapp/templates/taggit/tag_detail.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="row">
  <h2 class="mb-3 blog">{{ tag.name }}の記事一覧</h2>
  <div class="col-md-9">
    <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-3">
    {% for item in tag_posts %}
      <div class="col">
        <div class="card h-100">
          <div style="width: 100%; height:250px;">
          <a href="{% url 'myapp:post_detail' item.id %}">
            {% if item.thumbnail %}
              <img
                src="{{ item.thumbnail.url }}"
                class="card-img-top w-100 h-100"
                alt="{{ item.title }}" 
                style="object-fit: cover;"
              />
            {% else %}
              <img
                src="https://mdbootstrap.com/img/new/standard/city/044.jpg"
                class="card-img-top w-100 h-100"
                alt="{{ item.title }}" 
                style="object-fit:cover;"
              />
            {% endif %}
          
          </a>
          
          </div>
          <div class="card-body">
            <h4 class="card-title">{{ item.title }}
            </h4>
            <div class="d-flex justify-content-center">
              <a href="{% url 'myapp:like_add' item.pk %}" style="margin: 0 .25em">
                Like:<i class="far fa-thumbs-up" style="padding: 0 .5em;"></i>{{ item.like_count }}
              </a>
              <a href="{% url 'myapp:dislike_add' item.pk %}" style="margin: 0 .25em">
                Dislike:<i class="far fa-thumbs-down" style="padding: 0 .5em;"></i>{{ item.dislike_count }}
              </a>
            </div>
            <hr>
            <p class="fs-10 fw-normal">
              分類：{{ item.category }}
            </p>
            <div>
              タグ：
              <ul class="px-0">
                {% for tag in item.tags.all %}
                <a href="{% url 'myapp:tag_detail' tag %}">
                  <li class="btn btn-success btn-rounded-3 px-1 py-1" style="font-size: .5em;">{{ tag }}</li>
                </a>
                {% endfor %}   
              </ul>
            </div>
            <p class="card-text">
              {{ item.content |striptags| truncatechars:50 }}
            </p>
          </div>
          <a href="{% url 'myapp:post_detail' item.id %}" type="button" class="btn">Read more</a>
          <div class="card-footer">
            <small class="text-muted d-block text-center">更新日：{{ item.updated_at | date:"Y-m-j H:i" }}</small>
            <small class="text-muted d-block text-center">author : {{ item.author }}</small>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>

  <div class="col-md-3 d-flex flex-column p-3">
      <h5 class="blog">{{ tag.name }}のタイトル一覧</h5>
      <ul class="list-group list-group-flush">
        {% for item in tag_posts %}
          <li class="list-group-item" class="list-item">
            <a href="{% url 'myapp:post_detail' item.id %}">
              {{ item.title }}
            </a>
          </li>
               {% empty %}
      <p>
        このタグに属する記事は投稿されていません。
      </p>
        {% endfor %}
      </ul>
      <div class="d-flex align-items-center justify-content-center m-3">
        <a class="btn btn-outline-dark" href="{% url 'myapp:tag_list' %}">他のタグ</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

myapp/templates/taggit/tag_list.html
{% extends 'myapp/base.html' %} {% block content %}
<div class="row">
  <h2 class="mb-3 blog">Tag List</h2>
  <ul class="px-0">
    {% for item in tag_list %}

      
      <a href="{% url 'myapp:tag_detail' item %}" style="color: #fff;">
        <li
          class="btn btn-success btn-rounded-3 p-2 mx-1 m-2"
          style="font-size: 1em"
        >
        <font size={{tag.weight|floatformat:0}}>{{item }}</font>
      </li>
      </a>
    {% endfor %}
  </ul>
</div>
{% endblock %}