myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    # トップページのリンク
    path('likeordering', views.Indexlike.as_view(), name='indexlike'),
    # トップページのリンク(いいねの多い順)
    path('mypage', views.Mypage.as_view(), name='mypage'),
    # マイページのリンク
    path('post_create', views.PostCreate.as_view(), name='post_create'),
    # 新規投稿ページのリンク
    path(
        'post_detail/<int:pk>',
        views.PostDetail.as_view(),
        name='post_detail'),
    # 詳細画面表示
    path(
        'post_update/<int:pk>',
        views.PostUpdate.as_view(),
        name='post_update'),
    # 更新画面表示
    path(
        'post_delete/<int:pk>',
        views.PostDelete.as_view(),
        name='post_delete'),
    # 削除画面
    path('post_list', views.PostList.as_view(), name='post_list'),
    # リスト画面
    path('login', views.Login.as_view(), name='login'),
    # ログイン画面
    path('logout', views.Logout.as_view(), name='logout'),
    # ログアウト画面
    path('signup', views.SignUp.as_view(), name='signup'),
    # サインアップ画面
    path('like/<int:post_id>', views.Like_add, name='like_add'),
    path('dislike/<int:post_id>', views.DisLike_add, name='dislike_add'),
    # いいね・よくないね
    path('category_list', views.CategoryList.as_view(), name='category_list'),
    path(
        'category_detail/<str:name_en>',
        views.CategoryDetail.as_view(),
        name='category_detail'),
    # カテゴリー
    path('tag_list', views.TagList.as_view(), name='tag_list'),
    path(
        'tag_detail/<str:name>',
        views.TagDetail.as_view(),
        name='tag_detail'),
    # タグ
    path('search', views.Search, name='search'),
    # 検索


]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 追記

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager

# Create your models here.


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=50)
    name_en = models.CharField('カテゴリ名英語', max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def post_count(self):
        n = Post.objects.filter(category=self).count()
        return n

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)
    title = models.CharField('タイトル', max_length=50)
    content = RichTextUploadingField('内容', blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    thumbnail = models.ImageField(upload_to='images/', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)
    
    def like_count(self):
        n = Like.objects.filter(post=self).count()
        return n

    def dislike_count(self):
        n = DisLike.objects.filter(post=self).count()
        return n

    def get_previous_by_pk(self):
        queryset = type(self).objects.filter(pk__lt=self.pk).order_by('pk').last()
        if queryset:
            return queryset
        else:
            raise self.DoesNotExist("%s matching query does not exist." % self.__class__._meta.object_name)

    def get_next_by_pk(self):
        queryset = type(self).objects.filter(pk__gt=self.pk).order_by('pk').first()
        if queryset:
            return queryset
        else:
            raise self.DoesNotExist("%s matching query does not exist." % self.__class__._meta.object_name)

    def __str__(self):
        return self.title


class Like(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="投稿",
        on_delete=models.CASCADE)
    user = models.ForeignKey(
        User,
        verbose_name="LIKEしたユーザー",
        on_delete=models.CASCADE)


class DisLike(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name="投稿",
        on_delete=models.CASCADE)
    user = models.ForeignKey(
        User,
        verbose_name="DisLIKEしたユーザー",
        on_delete=models.CASCADE)

myapp/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'category', 'tags', 'thumbnail')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class SearchForm(forms.Form):
    freeword = forms.CharField(min_length=1, max_length=30, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

myapp/views.py
from django.shortcuts import resolve_url, redirect, render
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView, ListView
from .models import Post, Like, Category, DisLike
from django.urls import reverse_lazy
from .forms import PostForm, LoginForm, SignUpForm, SearchForm
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from taggit.models import Tag
from django.db.models import Count
# from django.core.paginator import Paginator


class OnlyMyPostMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        post = Post.objects.get(id=self.kwargs['pk'])
        return post.author == self.request.user


class Index(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')
        context = {
            'post_list': post_list,
        }
        return context


class Mypage(TemplateView):
    template_name = 'myapp/mypage.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-created_at')
        context = {
            'post_list': post_list,
        }
        return context


class Indexlike(TemplateView):
    template_name = 'myapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        post_list = Post.objects.all().order_by('-like')
        context = {
            'post_list': post_list,
        }
        return context


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super(PostCreate, self).form_valid(form)

        def get_success_url(self):
            messages.success(self.request, 'Postを登録しました。')
            return resolve_url('myapp:index')


class PostDetail(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        detail_data = Post.objects.get(id=self.kwargs['pk'])
        category_posts = Post.objects.filter(
            category=detail_data.category).order_by('-created_at')
        related_items = self.object.tags.similar_objects()

        params = {
            'object': detail_data,
            'category_posts': category_posts,
            'related_items': related_items,
        }
        return params


class PostUpdate(OnlyMyPostMixin, UpdateView):
    model = Post
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, 'Postを更新しました。')
        return resolve_url('myapp:post_detail', pk=self.kwargs['pk'])


class PostDelete(OnlyMyPostMixin, DeleteView):
    model = Post

    def get_success_url(self):
        messages.warning(self.request, 'Postを削除しました。')
        return resolve_url('myapp:index')


class PostList(ListView):
    paginate_by = 10
    model = Post

    def get_queryset(self):
        return Post.objects.all().order_by('-created_at')


class Login(LoginView):
    form_class = LoginForm
    template_name = 'myapp/login.html'


class Logout(LogoutView):
    template_name = 'myapp/logout.html'


class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'myapp/signup.html'
    success_url = reverse_lazy('myapp:index')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        self.object = user
        messages.success(self.request, 'ユーザー登録をしました。')
        return HttpResponseRedirect(self.get_success_url())


@login_required
def Like_add(request, post_id):
    post = Post.objects.get(id=post_id)

    is_liked = Like.objects.filter(user=request.user, post=post_id).count()
    like = Like()
    url = request.META.get('HTTP_REFERER')

    if is_liked > 0:
        messages.info(request, 'いいねを取り消しました。')
        Like.objects.filter(user=request.user, post=post_id).delete()
        return redirect(url)

    else:
        like.user = request.user
        like.post = post
        like.save()

        messages.success(request, '投稿にいいねしました！')
        return redirect(url)


@login_required
def DisLike_add(request, post_id):
    post = Post.objects.get(id=post_id)
    dislike = DisLike()
    is_disliked = DisLike.objects.filter(
        user=request.user, post=post_id).count()
    url = request.META.get('HTTP_REFERER')

    if is_disliked > 0:
        messages.info(request, 'よくないねを取り消しました。')
        DisLike.objects.filter(user=request.user, post=post_id).delete()
        return redirect(url)

    else:
        dislike.user = request.user
        dislike.post = post
        dislike.save()

        messages.warning(request, 'よくないねしました。')
        return redirect(url)


class CategoryList(ListView):
    model = Category


class CategoryDetail(DetailView):
    model = Category
    slug_field = 'name_en'
    slug_url_kwarg = 'name_en'

    def get_context_data(self, *args, **kwargs):
        detail_data = Category.objects.get(name_en=self.kwargs['name_en'])
        category_posts = Post.objects.filter(
            category=detail_data.id).order_by('-created_at')

        params = {
            'object': detail_data,
            'category_posts': category_posts,
        }

        return params


class TagList(ListView):
    model = Tag


class TagDetail(DetailView):
    model = Tag
    slug_field = 'name'
    slug_url_kwarg = 'name'

    def get_context_data(self, *args, **kwargs):
        tag_lists = Tag.objects.all().annotate(blog_count=Count(
            'taggit_taggeditem_items')).order_by('-blog_count')
        tag = Tag.objects.get(name=self.kwargs['name'])
        tag_posts = Post.objects.filter(tags=tag)

        params = {
            'tag': tag,
            'tag_lists': tag_lists,
            'tag_posts': tag_posts,
        }
        return params


def Search(request):
    if request.method == 'POST':
        searchform = SearchForm(request.POST)

        if searchform.is_valid():
            freeword = searchform.cleaned_data['freeword']
            search_list = Post.objects.filter(Q(title__icontains=freeword) | Q(
                content__icontains=freeword) | Q(
                author__username__icontains=freeword) | Q(
                    category__name__icontains=freeword) | Q(
                        tags__name__icontains=freeword)).distinct()

        params = {
            'search_list': search_list,
        }

        return render(request, 'myapp/search.html', params)


# Create your views here.

myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>{{ request.site.siteconfig.meta_title }}</title>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <style>
      a{
        color: #111;
        transition: .05s all ease !important;
      }

      a:hover{
        color: #1a0dab;
      }

      a.google{
        color:#1a0dab !important;
        font-weight: 400 !important;
      } 

      a.google:hover{ 
        text-decoration: underline;
      }

      a.google:visited{ 
        color: #660099;
      }

      h2.blog {
        padding: .5rem 1.5rem;
        border-left: 2px dotted #000;
      }
      h5.blog:first-letter{
        font-size: 150%;
        color: #eb6100;
      }
      img {
        max-width: 100%;
        height: auto;
        object-fit: contain;
      }
      .mathjax-latex{
        font-size: 1.1em;
      }

    </style>
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'myapp:index' %}">{{ request.site.siteconfig.top_title }}</a>
        {% comment %} <a class="navbar-brand p-0 m-0" href="{% url 'myapp:index' %}" style="width: 200px; height: 75px;">
          <img src="{% static 'img/logo_transparent.png' %}" alt="{{ request.site.siteconfig.top_title }}" class="d-inline-block align-top" style="width: 100%; height: 100%; object-fit: cover;">
        </a> {% endcomment %}
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'myapp:index' %}">Home</a>
            </li>
            {% comment %} <li class="nav-item">
              <a class="nav-link active" href="/admin" target="_blank">管理画面へ</a>
            </li> {% endcomment %}
            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="account"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
                Account
              </a>
              <ul
                class="dropdown-menu"
                aria-labelledby="account"
              >
                {% if request.user.is_authenticated %}
                  <li>
                    <a class="dropdown-item" href="{% url 'myapp:mypage' %}">{{ request.user }}</a>
                  </li>
                  {% comment %} {% for item in post_list %}
                    {% if request.user == item.author %}
                    アイウエオ
                    {% endif %}
                  {% endfor %} {% endcomment %}
                  <li>
                    <a class="dropdown-item" href="{% url 'myapp:logout' %}">ログアウト</a>
                  </li>
                {% else %}
                  <li>
                    <a class="dropdown-item" href="{% url 'myapp:login' %}">ログイン</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'myapp:signup' %}">ユーザー登録</a>
                  </li>
                {% endif %}
              </ul>
            </li>
            <!-- Dropdown -->
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
                Post
              </a>
              <ul
                class="dropdown-menu"
                aria-labelledby="navbarDropdownMenuLink"
              >
                <li>
                  <a class="dropdown-item" href="{% url 'myapp:post_create' %}">新規投稿</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'myapp:post_list' %}">投稿一覧</a>
                </li>
              </ul>
            </li>
            <!-- Dropdown -->
            {% comment %} <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false"
              >
                Category
              </a>
              <ul
                class="dropdown-menu"
                aria-labelledby="navbarDropdownMenuLink"
              >
                {% for item in category_list|slice:":4" %}
                  <li>
                    <a class="dropdown-item" href="{% url 'myapp:category_detail' item.name_en %}">{{ item.name }}</a>
                  </li>
                {% endfor %}
                <li class="border-top">
                  <a class="dropdown-item fw-bold" href="{% url 'myapp:category_list' %}">全てのカテゴリ</a>
                </li>
              </ul>
            </li> {% endcomment %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'myapp:category_list' %}">Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'myapp:tag_list' %}">Tag</a>
            </li>
          </ul>
          <form class="d-flex input-group w-auto" action="{% url 'myapp:search' %}" method="POST">
          {% csrf_token %}
            <input
              type="search"
              class="form-control"
              placeholder="記事を検索"
              aria-label="Search" 
              name="freeword"
            />
            <button
              class="btn btn-outline-primary my-0"
              type="submit"
              data-mdb-ripple-color="dark"
            >
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    <!-- Start your project here-->
    <main class="container mt-5 pt-5">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" role="alert">
          {{ message }}
        </div>
        {% endfor %}
      {% endif %}
      {% comment %} ↑更新時のメッセージ {% endcomment %}
      {% block content %} 
      {% endblock %}
    </main>
    <!-- End your project here-->
    <!-- footer -->
    <footer class="text-center text-lg-start bg-light text-muted ">
      <!-- Section: Social media -->
      <section
        class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom"
      >
        <!-- Right -->
      </section>
      <!-- Section: Social media -->

      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              {% comment %} <a class="navbar-brand p-0 m-0 d-inline-block w-100" href="{% url 'myapp:index' %}" style="width: 150px; height: 100px;">
                <img src="{% static 'img/logo_transparent.png' %}" alt="{{ request.site.siteconfig.top_title }}" class="d-inline-block align-top" style="width: 100%; height: 100%; object-fit: conver;">
              </a> {% endcomment %}
              <!-- Content -->
             <h6 class="text-uppercase fw-bold mb-4">
                {{ request.site.siteconfig.top_title }}
              </h6>
              <p>
                {{ request.site.siteconfig.top_subtitle|safe }}
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Useful links</h6>
              <p>
                <a href="{% url 'myapp:index' %}" class="text-reset">Home</a>
              </p>
              {% if request.user.is_authenticated %}
              <p>
                <a href="{% url 'myapp:logout' %}" class="text-reset">Logout</a>
              </p>
              {% else %}
              <p>
                <a href="{% url 'myapp:login' %}" class="text-reset">Login</a>
              </p>
              <p>
                <a href="{% url 'myapp:signup' %}" class="text-reset">Signup</a>
              </p>
              {% endif %}
              <p>
                <a href="{% url 'myapp:post_list' %}" class="text-reset">Post</a>
              </p>
              <p>
                <a href="{% url 'myapp:category_list' %}" class="text-reset">Category</a>
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
              <p>
              <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter  me-3"></i>
                <a href="https://twitter.com/gsexam_DB" target="_blank" rel="noopener noreferrer">
                twittter
                </a>
              </a>
              </p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                <a href="mailto:{{ request.site.siteconfig.mail }}">
                {{ request.site.siteconfig.mail }}
                </a>
              </p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->

      <!-- Copyright -->
      <div
        class="text-center p-4"
        style="background-color: rgba(0, 0, 0, 0.05)"
      >
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="/admin"
          >{{ request.site.siteconfig.author }}</a
        >
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->

    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
    <script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML">
  </script>
  </body>
</html>

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="row">
  <div class="col-md-6">
    <h2 class="blog">Logout</h2>
    <p>ログアウトしました。</p>
  </div>
</div>


{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}
{% block content %}
<div class="row mt-3 mb-5">
<div class="col-md-9">
  <div class="card">
    <div style="width: 100%; height: 50vh;">
      {% if object.thumbnail %}
        <img
          src="{{ object.thumbnail.url }}"
          class="card-img-top  w-100 h-100"
          alt="{{ object.title }}" 
          style="object-fit: cover"
        />
      {% else %}
        <img
          src="https://mdbootstrap.com/img/new/standard/nature/184.jpg"
          class="card-img-top  w-100 h-100"
          alt="{{ object.title }}" 
          style="object-fit: cover"
        />
      {% endif %}
    </div>
    <div class="card-body">
      <div class="row">
      <div class="col-xl-7 col-12">
        <h5 class="card-title p-3 blog">{{ object.title}}</h5>
      </div>
      <div class="col-xl-5">
        <div class="d-flex align-items-center h-100">
          <small class="text-muted d-block text-center p-1">投稿者 : {{ object.author }}</small>
          <small class="text-muted d-block text-center p-1">更新日：{{ object.updated_at | date:"Y-m-j H:i" }}</small>  
        </div>
      </div>
      
      </div>
      <hr>
      <p class="card-text">
        {{ object.content | safe }}
        <br>
      </p>
    <div class="card-footer">
      <div class="d-flex justify-content-center m-3">
        <a href="{% url 'myapp:like_add' object.pk %}" style="margin: 0 .25em" class="p-2">
          Like:<i class="far fa-thumbs-up" style="padding: 0 .5em;"></i>{{ object.like_count }}
        </a>
        <a href="{% url 'myapp:dislike_add' object.pk %}" style="margin: 0 .25em" class="p-2">
          Dislike:<i class="far fa-thumbs-down" style="padding: 0 .5em;"></i>{{ object.dislike_count }}
        </a>
      </div>
      <div class="d-flex align-items-center justify-content-center flex-column">
        <a href="{% url 'myapp:index' %}" class="btn btn-outline-dark m-4">ホームへ</a>
        <div class="d-flex align-items-center justify-content-center flex-wrap">
          {% if object.author == request.user %}
            <a href="{% url 'myapp:post_update' object.pk %}" class="btn btn-dark m-2">更新</a>
            <a href="{% url 'myapp:post_delete' object.pk %}" class="btn btn-danger m-2" >削除</a>
          {% endif %}
        
        </div>
      </div>
    </div>
    <div class="d-flex w-100 justify-content-between flex-wrap">
      <p class="p-2">
      {% with prev=object.get_previous_by_pk %}
        {% if prev %}
          
          <a href="{% url 'myapp:post_detail' prev.pk %}"><i class="fas fa-angle-double-left px-2"></i>{{ prev.title }}</a>
        {% endif %}
      {% endwith %}
      </p>

      <p class="p-2 d-inline-block w-100" style="text-align: end;">
     
      {% with next=object.get_next_by_pk %}
        {% if next %}
          
          <a href="{% url 'myapp:post_detail' next.pk %}">{{ next.title }}<i class="fas fa-angle-double-right px-2"></i></a>
        {% endif %}
      {% endwith %}
      </p>
    </div>

    </div>
  </div>
</div>
<div class="col-md-3">
  <div class="card my-3">
    <div class="card-body">
      <h5 class="card-title mb-3 blog">{{ object.category }}</h5>
      <p class="fs-6">このカテゴリーの他の記事</p>
      <ul class="list-group list-group-flush">
        {% for item in category_posts|slice:":5" %}
          <li class="list-group-item">
            <a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="d-flex align-items-center justify-content-center m-3">
        <a class="btn btn-outline-dark" href="{% url 'myapp:category_list' %}">全て表示</a>
      </div>
  </div>
  <div class="card my-3">
    <div class="card-body">
      <h5 class="card-title mb-3 blog">関連記事</h5>
      <ul class="list-group list-group-flush">
        {% for item in related_items|slice:":10" %}
        <li class="list-group-item">
          <a href="{% url 'myapp:post_detail' item.id %}">{{ item.title }}</a>
        </li>
        {% empty %}
        <p>関連記事はありません</p>
        {% endfor %}
      </ul>
    </div>
    {% comment %} <div class="d-flex align-items-center justify-content-center m-3">
        <a class="btn btn-outline-dark" href="{% url 'myapp:category_list' %}">全て表示</a>
      </div> {% endcomment %}
  </div>
</div>
</div>
{% endblock %}